# Household Resilience Trip-Wire Configuration
# Based on "Risk and Household Resilience" document H1-H6 analysis

monitoring:
  enabled: true
  check_interval_minutes: 60
  data_retention_days: 365
  max_retries: 3
  timeout_seconds: 30

# Trip-wire thresholds per research document
trip_wires:
  treasury_tail:
    name: "10-yr Treasury Auction Tail"
    enabled: true
    source_type: "api"
    url: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/auction_results"
    thresholds:
      green: 3.0      # < 3 bp
      amber: 7.0      # 3-7 bp  
      red: 999.0      # > 7 bp (any value above amber)
    unit: "basis_points"
    
  ice_detention:
    name: "ICE Detention Bed Fill Rate"
    enabled: true
    source_type: "manual"  # Requires weekly PDF processing
    thresholds:
      green: 0.65     # < 65%
      amber: 0.85     # 65-85%
      red: 999.0      # > 85%
    unit: "percentage"
    
  taiwan_exclusion:
    name: "PLA Taiwan Exclusion Zone"
    enabled: true
    source_type: "rss_social"
    sources:
      - "https://twitter.com/CSIS_Taiwan"
      - "Reuters Taiwan exclusion zone"
    thresholds:
      green: "NONE"
      amber: "TEMP" 
      red: "BLOCKADE"
    unit: "status"
    
  hormuz_risk:
    name: "Hormuz War Risk Premium"
    enabled: true
    source_type: "financial_data"
    sources:
      - "Lloyd's List WRI"
      - "S&P Platts"
    thresholds:
      green: 1.5      # < 1.5%
      amber: 4.0      # 1.5-4%
      red: 999.0      # > 4%
    unit: "percentage"
    
  dod_autonomy:
    name: "DoD Auto-Execute Wording"
    enabled: true
    source_type: "government_data"
    url: "https://sam.gov"
    search_terms: ["decision authority autonomous"]
    thresholds:
      green: "HUMAN VETO"
      amber: "PILOT"
      red: "REMOVED"
    unit: "status"
    
  mbridge_crude:
    name: "mBridge Gulf Crude Settlement"
    enabled: true
    source_type: "financial_report"
    sources:
      - "BIS Project mBridge"
      - "IMF working papers"
    thresholds:
      green: 5.0      # < 5%
      amber: 25.0     # 5-25%
      red: 999.0      # > 25%
    unit: "percentage"
    
  jobless_claims:
    name: "Weekly Jobless Claims"
    enabled: true
    source_type: "api"
    url: "https://api.stlouisfed.org/fred/series/observations"
    thresholds:
      green: 250      # < 250k claims
      amber: 275      # 250-275k
      red: 350        # > 350k (recession signal)
    unit: "thousands"
    
  luxury_collapse:
    name: "Luxury Collapse Index"
    enabled: true
    source_type: "composite"
    sources:
      - "Chrono24 Rolex prices"
      - "JetNet bookings"
      - "Luxury real estate"
    thresholds:
      green: 15       # < 15 on index
      amber: 25       # 15-25
      red: 40         # > 40 (mass liquidation)
    unit: "index"
    
  pharmacy_shortage:
    name: "Critical Drug Shortages"
    enabled: true
    source_type: "government_data"
    url: "https://www.fda.gov/drugs/drug-shortages"
    thresholds:
      green: 5        # < 5 drugs
      amber: 8        # 5-8 drugs
      red: 15         # > 15 drugs
    unit: "count"
    
  school_closures:
    name: "School District Closures"
    enabled: true
    source_type: "aggregated"
    sources:
      - "Major district websites"
      - "State education departments"
    thresholds:
      green: 2        # < 2 district-days
      amber: 3        # 2-3 district-days
      red: 10         # > 10 district-days
    unit: "district_days"
    
  agi_milestones:
    name: "AGI Development Milestones"
    enabled: true
    source_type: "composite"
    sources:
      - "arXiv AI papers"
      - "OpenAI/Anthropic/DeepMind announcements"
      - "AI benchmark leaderboards"
    thresholds:
      green: 40       # < 40% capability score
      amber: 40       # 40-70% 
      red: 70         # > 70% (imminent AGI)
    unit: "milestone_score"
    
  labor_displacement:
    name: "AI Labor Displacement Rate"
    enabled: true
    source_type: "composite"
    sources:
      - "BLS employment data"
      - "Tech layoff trackers"
      - "Industry automation reports"
    thresholds:
      green: 20       # < 20% displacement index
      amber: 20       # 20-35%
      red: 35         # > 35% (mass unemployment)
    unit: "displacement_index"

# Alert system configuration
alerts:
  tighten_up_threshold: 4  # Number of red alerts to trigger "TIGHTEN-UP" (33% of 12 indicators)
  notification_methods:
    - email
    - desktop
  
  # Notification settings (actual credentials in secrets.yaml)
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    from_email: "${EMAIL_FROM}"
    to_emails:
      - "${EMAIL_TO_PRIMARY}"
      - "${EMAIL_TO_SECONDARY}"
  
  sms:
    provider: "twilio"
    account_sid: "${TWILIO_SID}"
    auth_token: "${TWILIO_TOKEN}"
    from_number: "${TWILIO_FROM}"
    to_numbers:
      - "${SMS_TO_PRIMARY}"

# Phase mapping based on resilience roadmap document
phases:
  phase_0: "Foundations - skill & brain-set"
  phase_1: "72-hour life-support bin"
  phase_2: "Comms & digital resilience"
  phase_3: "Air, health & mobile comms"
  phase_4: "Dry-basement assurance"
  phase_5: "Tank → generator plumbing prep"
  phase_6: "Secure-shelter nook build"
  phase_7: "Harden + standby generator"
  phase_8: "Rainwater & circuits"
  phase_9: "Optional ICC-500 safe-room"

# Logging configuration
logging:
  level: "INFO"
  file: "logs/monitoring.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
